//
//  TipsModel.swift
//  FashionTips
//
//  Created by Natalie Lim on 7/6/16.
//  Copyright © 2016 Natalie Lim. All rights reserved.
//

import GameKit

struct TipModel {
    let tips = ["Show skin strategically - If it's cleavage, don't show your legs. If it's your legs, stay covered on top.",
    "Accessorize with bright colors; if you have a neutral colored closet, bold colored shoes or bags will add energy and a pop!",
    "If you find an especially flattering fit right off the rack, go ahead and buy doubles. When it works, why question it?",
    "The secret formula for a soft but form fitting tee: 95% cotton, 5% Lycra spandex. For jeans to hold their shape, they need at least 2% Lycra.",
    "Hem your pants to a shoe height - generally, hems should just graze the tops of your shoes and be from 1/2 inch to 3/4 inch off the floor.",
    "'Once you know which silhouettes flatter you, filter trends ruthlessly.' - designer Shoshanna Gruss",
    "Make a list before you shop of the 10 fave items in your closet. This will help you zero in on pieces that mesh with what you own.",
    "'Hoop earrings are a classic style that every woman—regardless of age—should have, but the type depends on your face. If you have a thin face, go for larger round or embellished hoops. If you have a round face an elongated hoop or drop style is best.' - Elena Kiam, Creative Director, Lia Sophia",
    "'Always organize your clothes going light to dark from left to right in your closet. Your eye will follow the color and thus help you stay organized.' - Melanie Charlton Fascitelli, Founder, Clos-ette and Clos-ette Too." ,
    "Freeze jeans inside a plastic bag for two days to zap odor without running them through the washing machine.",
    "Looking for an easy trick to make your bare legs look longer? Try pumps the same color of your skin, which gives give the illusion that your legs extend a few extra inches.",
    "'It's a myth that loose styles flatter a large bust or a plus-size woman. The area just under the bust is a woman's smallest torso measurement, so emphasizing it with a structured waistband that hits higher than your natural waist will make you look a size smaller.' - BG Krishnan, President, eShakti.com",
    "Never put a garment on immediately after ironing, as this can actually cause new wrinkles to form. Instead, let it sit for five minutes to set the press.",
    "Use shaving cream and a washcloth to remove liquid makeup from shirt collars.",
    "Break in stiff or too-snug shoes by slipping them on with socks and blasting your feet with a hot hairdryer.",
    "Before bed, pour two or three tablespoons of baking soda into sweaty workout sneakers and tilt the shoe to distribute the soda evenly. This will eat any odor and absorb perspiration.",
    "'For guaranteed weight loss, I advise people to follow my A, B, C's – no Alcohol, Bread or processed Carbs.' - David Kirsch, celebrity trainer and fitness guru",
    "Pile on good accessories (scarves, sunglasses, hats, statement jewelry) to instantly transform even the most basic outfit",
    "Confused about laundry settings? Remember this: The hotter the water, the cleaner the clothing will be. While warm water is fine for most clothes, linens and dirty white clothing are best washed in hot water to remove germs and heavy soil. Cold water is usually used for delicates.",
    "After a shower, use your hairdryer to de-mist bathroom mirrors in seconds.",
    "When cleaning out your closet, ask a friend whose style you admire to come over and help. She/he might offer new insight on how to wear certain items before you toss them.",
    "Looking for uses for all the single socks you've amassed while doing laundry? When you've got aches or pains, fill a sock with dry beans or rice and pop it in the microwave for 30 seconds. Voila, an instant (and free) heating pad.",
    "Who has the time to hand wash bras? Machine wash them in cold water in a mesh zipper bag and drape them over a hanger to air dry.",
    "Use a lemon wedge to remove excess or streaky self-tanner.",
    "Track lighting is possible even for the tiniest closet: Buy a track kit, screw it into the ceiling, run the wire down the wall and plug it into the nearest outlet. Not only will you see all your clothes better, but you'll feel like you have a more luxurious closet.",
    "Wear your new real leather jacket in the rain to break it in. Water will soften up the leather and allow it to stretch and crease at specific points on your body.",
    "Invest in silk or satin pillowcases to keep your hair from breaking during the night. (They also keep your skin looking smoother than rough cotton cases!)",
    "If you're unsure about an impulse or sale purchase, leave it at the store. If you're still thinking about it when you wake up the next day, buy it.",
    "A good shoemaker can fully rebuild your favorite pair, even if the arch is cracked",
    "To coax a loose thread back into place, gently tug at the stitches to the sides of the pull as well as above and below",
    "There's nothing cooler than sticking to a signature style you know looks good on you. Slaves to fashion are never chic!",
    "It might sound 'budget', but a hot glue gun works amazingly well to hem skirts, pants and even jeans in a pinch.",
    "A structured hat should rest about 1/8 to a 1/2-inch above the ears.",
    "'Never dry a wet shoe with heat. Let it dry naturally in open air. Heat will dry out leather and the lifespan of the shoe will be cut in half.' - Jordan Adoni, Designer, Modern Vice",
    "The easiest way to make your closet look organized: Buy all the same hangers for everything–same color, same shape.",
    "When it doubt, always choose the smaller denim size, since jeans stretch with wear.",
    "Wrap an empty bottle of your favorite perfume in a handkerchief and tuck it into your underwear drawer for a subtle scent.",
    "Heat can warp your glasses frames, so always keep them in a hard case and never wear them on your head on a hot day.",
    "Spray shirts prone to sweat stains with lemon juice before washing. The natural acid dissolves alkaline sweat residue that could cause yellow discoloration.",
    "V-neck sweaters and tees give the illusion of a longer torso.",
    "Spritzed a bit too much perfume on yourself this morning? Use unscented, oil-based makeup remover to remove excess perfume.",
    "Tend to wear certain leather shoes without socks? Always stuff them with a soft cloth when you're done wearing them. This absorbs moisture and help the shoes keep their shape.",
    "'The best way to store fashion jewelry, including Sterling Silver, is in Ziploc bags. This helps pieces retain luster and reduces tarnishing and scratches.' - Jordann Weingartner, Founder, I Love Jewelry Auctions",
    "Still look chic while showing some skin: If you're wearing a miniskirt or shorts, cover up on top. If your top is skimpy, go for full-coverage bottoms.",
    "Pants a bit too tight? Let them air dry and stretch the waistband by hand (or with a hairdryer) while they're still damp.",
    "Ideally, a pencil skirt should hit just at the top of your knee. Any lower and it will start to shorten your leg.",
    "Everyday bras should be replaced every three to six months, as that's when they start to lose elasticity and support.",
    "'Marquise ring shapes help to create the illusion of longer, more slender fingers, even on small wide hands. Pear or oval stones are also flattering.' - Carol Brodie, Fine Jewelry Designer, HSN's Rarities: Fine Jewelry with Carol Brodie",
    "How to care for fur at home: 'Pass the fur with a hairbrush and steam it for added bounce, volume and shine.' - Eran Elfassy, Co-Creative Director, Mackage",
    "To determine if pearls are real, lightly rub them over your teeth. Fake pearls will be perfectly smooth, and real ones will feel slightly gritty or textured.",
    "Don't underestimate the power of a well-fitting, stylish winter coat. You can be wearing pajamas underneath and you'll still look perfectly put together.",
    "Windex restores the glossy sheen on patent leather without doing any damage.",
    "Fold jeans like a pro: Lay jeans on a flat surface, fold in half from left to right. Grab the stacked jean legs and fold them in half so the hem of the jeans lines up with the waistband. Fold the jeans in half one more time.",
    "When you're shopping for a jacket, coat, or blazer, pay attention to the fit around the shoulders. While a tailor can tweak pretty much everything about the fit of a jacket - from tapering the waist to shortening it - they can't change the shoulders. Make sure the seams sit perfectly at the bony tops of your shoulders.",
    "'To remove watermarks from leather boots, add a few drops of vinegar to a bowl of cool water and scrub the stains with a soft bristle brush until stains are no longer visible. Let dry overnight.' - Daryl Carr, Marketing Coordinator, Stetson",
    "Hang a shoe bag on the back of your bathroom door and use it to hold makeup, toiletries, brushes, hair ties, etc.",
    "A vintage trunk not only makes a stylish coffee table, but can also house shoes and clothing you rarely wear.",
    "Due to its high level of surfactants, Dawn dish detergent is especially successful at removing grease and oil stains from clothing.",
    "'A flattering silhouette begins with the right underpinnings. Never underestimate the power of Spanx - they're a girl's best friend!' - Lucy Sykes Rellie, Fashion Director, Rent the Runway",
    "Revamp an old coat by swapping out the buttons and having a tailor replace the lining with something eye-catching, like a pattern or a bright color.",
    "You can get away with wearing a pair of nice jeans and a T-shirt nearly anywhere (yep, even work!) if you amp up to the look with accessories. Try throwing on a statement necklace, an intricate bracelet, or even some standout earrings.",
    "Adding a textured, embellished, or a great colored belt is the fastest way to pull together the most basic pieces or quickly elevate a casual outfit",
    "A pair of pointed-toe black pumps are essential - they're seasonless, crazy flattering, and you can wear them with absolutely anything.",
    "According to Lauren Edelstein, Style Director at Shopbop, all you need to do to determine whether or not a pair of jeans will fit is to wrap the waist around your neck — if the ends meet without overlapping (or stretching), they'll fit your waist.",
    "For instant longer-looking legs wear shoes in the same color as your pants.",
    "Never underestimate the power of good accessories. Dress up plain outfits with the addition of a scarf, belt, or piece of jewelry.",
    "Stick to one focal point accessory. For example, if you're wearing a big statement necklace, keep your earrings small or skip them altogether.",
    "Never base your outfit on more than three colors. It just ends up looking like a hot mess. And make sure you don't OVER-accessorize.",
    "Let accessories run the conversation. Never leave home without a statement piece. A handbag is a good way out...",
    "'Red lipstick... it's the ultimate for glamour' - Dolce & Gabbana",
    "'A personal scent: choose The One for you.' - Dolce & Gabbana",
    "'Fine or or costume jewellery - blend them tastefully.' - Dolce & Gabbana",
    "Eyewear is a versatile accessory, choose an everyday pair and get yourself some moody ones to underline your style.",
    "Mix and match prints - dare and you will be amazed by the freshness and sophistication they bring to an outfit.",
    "Layer knits on lace, suggest femininity by playing with contrasts.",
    "'Save time and energy by repeating your favorite outfits.' - Arianna Huffington",
    "Invest in your beauty and health by encasing your bed with pure silk - beauty sleep isn't actually a myth.",
    "Jeans will stretch after two washes. When it comes to altering them, make sure you've washed them twice before you visit your tailor. All hems of your jeans should go up to the tops of your shoes.",
    "A comfortable outfit is a must for a fun night out. Choose your clothing items carefully, or you might end up fixing up your outfit every couple of minutes, which is no fun at all Start by choosing shoes which are comfy, and coordinate your outfit with them.",
    "Classic colors like black, navy, white, gray or red as an accent always look modern, chic, rich, and relevant.",
    "Check out clothing in different lighting, because some garments may be see-through during the day or under bright lights",
    "Keep a spare garment with you, just in case.",
    "Accidents happen, so have a spare clothing item nearby at all times possible. Start by taking something to your office (perhaps a white button-down shirt, which is a classic) which will probably be able to fit in your outfit.",
    "Forget about obvious color breaks and create the illusion of length by mixing and matching different textures and fabrics in the same or similar shade to create interest. Dark shades are best but you can create the same vibe if you stay monochromatic.",
    "A handbag is one of the most versatile and important accessories that a woman can own. You should at least have three different kinds for starters – small, medium and large.",
    "Devoting this much time to your closet is unnecessary if you don't take care of all those clothes you've carefully chosen. One quality iron, a nice detergent and a couple of seconds you should devote to checking the instructions on a garment is all it takes, so don't be lazy.",
    "How to wear jeans: 1 roll for flats, 2 rolls for ankle boots or high heels, long and slouchy for pumps, pegged boyfriends with heels, only the skinniest with boots (no creepy bunching allowed), platforms with high waisted flares.",
    "Wear darker colored pants if you don't want to draw attention to hips/thighs.",
    "How to wear a jean jacket: buttoned and belted, Jenna Lyons style (worn with a formal skirt), layered under another jacket, over a chambray shirt (make sure they are two obviously different shades of denim), to 'boy' up a flirty dress, classic (with the sleeves pushed up and the collar popped on top of an old tee.",
    "How to wear a scarf: like a bandit (with a rockin' tee), classic French girl (with a Breton top), classic rich girl (with a sweater-girl sweater), drapey (under the lapel of a blazer), gathered (over the collar of a crisp white shirt), bowed (with a cardigan).",
    "When all else fails, follow this simple but effective fashion formula: 1 basic (dark jeans, pencil skirt, basic top) + 1 interest piece (color, pattern, texture, shine) + 1 completer piece (jacket, cardigan, belt) + accessories (bag, jewelry, clutch, shoes)",
    "Dressing for your size doesn't just mean nixing clothes that are too tight from your wardrobe. It also means you shouldn't wear clothes that are too baggy. Both will make you look frumpy.",
    "Make sure you can walk in them: There are some occasions we'd sacrifice comfort for fashion. After all, four inch heels guarantee that legs-for-miles look. But if it looks better than it actually feels on your foot, you probably won't wear it. Don't waste your money (or endure the pain)",
    "Button down blouses are intended to do one thing and one thing alone — stay buttoned down. It looks sloppy if we can see what lies beneath your shirt.",
    "Worried about your waist or hips? Try peplum for an instant slimming effect. It flatters every figure and does wonders at hiding unsightly bulge.",
    "Try on 3 sizes, not one. Shoe sizes vary among designers and brands. Start by trying on your usual shoe size, then try on one pair that's a half-size smaller and a second pair that's a half-size larger. When in doubt, buy the shoes that are a half-size larger.",
    "Figure out if the undertones in your skin are either warm or cold. Women with cool undertones usually look best in white, black, gray, silver, and shades of blue. Women with warm undertones will be dazzling in shades of yellow, gold, brown, green and red.",
    "Double-sided tape is a dream come true: Keep plunging necklines in place and prevent any fashion mishaps with this godsend.",
    "Rain or shine, always be trendy and chic with an ultra cute umbrella! Get yourself a colorful, knock-out umbrella that makes you stick out.",
    "Wine bottles have another use — place them inside your boots to make them stand upright.",
    "Make sure you know your arch type before shoe shopping. An easy way to determine your arch is to step on a piece of paper after wetting the bottom of your foot. You can determine whether you have a normal, flat or high arch by examining your wet footprint. If the middle part of your footprint doesn't show up, you have a high arch, but if you can see most of your footprint then you have a fairly flat arch. Your arch is normal if you see half of your wet footprint.",
    "Stop hoarding. If you haven't worn it recently, then you probably never will. If it's been over a year, nix it. Donate clothes you'll never wear.",
    "Learn to pack lightly - it's an art. You can follow this rule-of-thumb: If you're going away for one week, pack three bottoms and 3 shirts per bottom. For two weeks pack five bottoms. For every dress you pack, you can lose a shirt and a bottom.",
    "Change purses can be useful, but if yours rarely sees daylight, either because you don't put change in it, or worse, never take change out of it (this is just dead weight), then it's time to say goodbye.",
    "Limit Accessories. If you're throwing yourself an arm party, then it might be better to steer clear of too many rings. If you're wearing large earrings that scream for attention, then you might want to forgo an equally radiant necklace - they will only work against each other.",
    "A purse isn't just a fashion statement. It's main purpose is functional. You carry it around wherever you go so it needs to contain some essentials: your wallet, a pen, painkillers, hand sanitizer, tissues, make-up essentials, hand cream, gum or breath mints, something for that time of month, and for those of you who spend lengthy bouts talking, texting or gaming, bring your phone charger along.",
    "When in doubt, overdress. There's nothing worse than showing up an event underdressed. Maybe the invite didn't specify or involved the word casual - but everyone else dressed up not so casually. There's no harm in looking too pulled together.",
    "Wear nice underwear every day, it will make you feel special. Sure, not everyone gets to be so lucky and see how nice your underwear is, but you'll know. Also, be sure to get your bras fitted - often. It will make your clothes hang better and be infinitely more comfortable.",
    "Invest in a quality wallet, one that reflects your signature style. It may spend most of its time in your purse but your wallet is just as important as your purse.",
    "If you're out of shoe polish, the staff at Woman's Day suggest rubbing a bit of lotion on your shoes. It works well on the tips of pointed shoes and increases the longevity of leather by keeping it supple.",
    "Make lists your best friend if you love shopping. They will make your life easier. Not only will they keep your focus on the items you actually need, they'll cut down the amount of time you spend shopping and prevent you from making impulse purchases (hopefully).",
    "Have ready-to-wear ensembles hanging in your closet (yes, even the shoes and if you're really keen, the accessories too). They will come in handy when you either have absolutely nothing to wear or when you're in a rush to pull an outfit together. It's better to have a few for different occasions --one corporate, one casual and one glamourous look.",
    "How to wear denim on denim: The style experts at Refinery 29 say that doubling up on denim can work if you wear dark slim-fitting pants and a lighter slim-fitting top. You might want to break up the jean look by adding a cute belt.",
    "Know your essentials and basics and stock up. These can include white and black blouses, a little black dress, high heels, red lipstick, diamond studs, blue jeans and anything else that has a central role in your style. Remember, these looks are timeless so investing in certain items that are more expensive but higher in quality may be wiser because they will last longer.",
    "Don't pretend it fits: We've all been there, standing in the dressing room and convincing ourselves that the button will magically stay closed when we get home (and then, of course, it doesn't). These are the times where we have to accept that our bodies have changed in one way or another, and buy clothes that fit.",
    "Go nude when you wear white. White is a tricky colour to wear, so if you're wearing white pants, don't wear black or white underwear because it will still be visible through your pants. Instead, buy nude underwear. It's more discreet.",
    "Dress your age. Let's face it, it's a tad tacky when 50-somethings try sporting an outfit you'd normally find on 20-somethings - and vice versa. However, tinsel town allows celebrities more leeway than the real world does for us ordinary folk. As a rule of thumb, stick to age appropriate attire.",
    "Main-stream fashion trends change to fast to make useful wardrobe staples. Ignore fashion trends. Models get paid to make goofy clothes seem reasonable. Don't fall for it.",
    "Long sleeves were meant to be rolled, right? While a button-down can feel stiff, rolling up the sleeves gives it an easy nonchalance. It's the easiest way to inject a little cool factor into even your most classic shirts.",
    "The hemlines of our jeans might just cover up the best part of our outfits - the shoes, of course! - if we didn't roll them up. Instead of rolling up under the hem for a discreet, 'looks like I didn't cuff them at all' look, embrace the roll. The result is cool and a little undone - and perfect for showing off your heels.",
    "'Put some shine on your shoes. They may not be the first thing you think about, but a fresh shine makes all the difference. Not only does it look snappier, but your kicks will live longer, too.' - Men's designer Billy Reid. ",
    "There's more than one way to cuff jeans - from a single roll to a double, find your style and master the look you want. A single cuff works well with stiffer, straight-leg denim, while a rolled cuff goes well with a baggier, boyfriend jean.",
    "Nothing says 'fashion' like a draped jacket over the shoulders. Crazy, but true — it costs nothing and makes your outfit look infinitely more expensive and chic.",
    "The easiest way to define a waistline without a belt is knotting your shirt right at the middle. It lends a more creative finish than just tucking in your shirt and adds a playful touch.",
    "It makes it easy to turn a dress into a skirt if you add a button-down or a tee over the top half and tie it at the waist to create the illusion of separate bottom half.",
    "Try out the 'half tuck' sometime. Rather than tuck in the whole shirt, this look conveys a more casual, current vibe that turns even a jeans and t-shirt outfit into more of a statement. Tuck half the shirt or the whole front and let the tail hang over the waistline.",
    "Transform oversized shirts, tunics, and coats to fit to your frame with a belt. This will define your shape and highlights your middle, plus, the belt adds polish to even the most casual ensembles. It may take a minute to throw on, but it looks like a more complete outfit every time, and ensures that your coat will stay in place all night."
    ]

    func getRandomTip() -> String {
        let randomNumber = GKRandomSource.sharedRandom().nextIntWithUpperBound(tips.count)
        
        return tips[randomNumber]
        
    }
}

